#!/usr/bin/env python3
"""
extract_dialogue.py — Extract all msgbox calls from OW map scripts, grouped by area.

Usage:
    python3 tools/extract_dialogue.py [--out <path>]

Outputs a markdown document with every msgbox string grouped by map file.
"""

import re
import sys
import os
from pathlib import Path

MAPS_DIR = Path(__file__).parent.parent / "data" / "maps"
DEFAULT_OUT = Path(__file__).parent.parent / "tools" / "dialogue_dump.md"

# Maps in logical play order / area groupings
AREA_GROUPS = [
    ("Intro",       ["ow_Intro_PokemonCenter"]),
    ("Kolchavi",    ["ow_Kolchavi", "ow_Kolchavi_House1", "ow_Kolchavi_House2",
                     "ow_Kolchavi_House3", "ow_Kolchavi_House4", "ow_Kolchavi_House5",
                     "ow_Kolchavi_PokemonCenter", "ow_Kolchavi_MaritimeGuildhall",
                     "ow_Kolchavi_Lab_1F", "ow_Kolchavi_Lab_2F"]),
    ("Floran",      ["ow_Floran", "ow_Floran_House1", "ow_Floran_House2",
                     "ow_Floran_House3", "ow_Floran_House4", "ow_Floran_House5",
                     "ow_Floran_PokemonCenter", "ow_Floran_Warehouse", "ow_Floran_WestmarkHq"]),
    ("Route 3",     ["ow_r3"]),
    ("Route 6",     ["ow_r6"]),
    ("Route 8",     ["ow_r8", "ow_r8_House1"]),
    ("Route 10",    ["ow_r10", "ow_r10_House1"]),
    ("Route 12",    ["ow_r12", "ow_r12_House1"]),
    ("Sowback Cave",["ow_SowbackCave_1F", "ow_SowbackCave_2F",
                     "ow_SowbackCave_B1F", "ow_SowbackCave_B2F"]),
]

def extract_msgboxes(pory_path: Path) -> list[dict]:
    """Return list of {script, speaker, lines} for each msgbox in the file."""
    text = pory_path.read_text(encoding="utf-8")
    results = []
    current_script = "(unknown)"
    current_speaker = None

    # Split into logical lines, preserving multi-line msgbox strings
    # We process token by token using a simple state machine
    lines = text.split("\n")

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Track current script name
        script_match = re.match(r'^script\s+(\w+)\s*\{', stripped)
        if script_match:
            current_script = script_match.group(1)
            current_speaker = None

        # Track setspeaker
        speaker_match = re.match(r'setspeaker\s*\(\s*"([^"]+)"\s*\)', stripped)
        if speaker_match:
            current_speaker = speaker_match.group(1)
        elif re.match(r'setspeaker\s*\(\s*NULL\s*\)', stripped):
            current_speaker = None

        # Detect msgbox (may span multiple lines)
        if re.match(r'msgbox\s*\(', stripped) or re.match(r'message\s*\(', stripped):
            # Collect the full msgbox call (handles multi-line format() calls)
            call_lines = [stripped]
            depth = stripped.count("(") - stripped.count(")")
            j = i + 1
            while depth > 0 and j < len(lines):
                next_line = lines[j].strip()
                call_lines.append(next_line)
                depth += next_line.count("(") - next_line.count(")")
                j += 1

            full_call = " ".join(call_lines)

            # Extract the string content (everything inside the outer quotes)
            # Handles: msgbox("text") and msgbox(format("text"), TYPE) and message(format(...))
            string_match = re.search(r'"((?:[^"\\]|\\.)*)"', full_call)
            if string_match:
                content = string_match.group(1)
                results.append({
                    "script": current_script,
                    "speaker": current_speaker,
                    "text": content,
                })
            i = j
            continue

        i += 1

    return results


def map_short_name(map_dir: str) -> str:
    return map_dir.replace("ow_", "").replace("_", " ")


def run(out_path: Path):
    lines_out = ["# Dialogue Dump — OW Maps\n",
                 "_Generated by `tools/extract_dialogue.py`. Re-run to update._\n"]

    for area_name, map_dirs in AREA_GROUPS:
        lines_out.append(f"\n---\n\n## {area_name}\n")

        for map_dir in map_dirs:
            pory = MAPS_DIR / map_dir / "scripts.pory"
            if not pory.exists():
                lines_out.append(f"\n### {map_short_name(map_dir)}\n_(file not found)_\n")
                continue

            entries = extract_msgboxes(pory)
            if not entries:
                lines_out.append(f"\n### {map_short_name(map_dir)}\n_(no msgbox calls)_\n")
                continue

            lines_out.append(f"\n### {map_short_name(map_dir)}\n")

            current_script = None
            for entry in entries:
                if entry["script"] != current_script:
                    current_script = entry["script"]
                    lines_out.append(f"\n**`{current_script}`**\n")

                speaker = f"[{entry['speaker']}] " if entry["speaker"] else ""
                # Render control codes as readable text
                text = entry["text"]
                text = text.replace(r"\p", " ¶ ").replace(r"\N", " ").replace(r"\n", " ").replace(r"\l", " ")
                lines_out.append(f"> {speaker}{text}\n")

    out_path.write_text("\n".join(lines_out), encoding="utf-8")
    print(f"Written to {out_path}")


if __name__ == "__main__":
    out = Path(sys.argv[sys.argv.index("--out") + 1]) if "--out" in sys.argv else DEFAULT_OUT
    run(out)
